apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-processor
  namespace: flowlog
  labels:
    app: log-processor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: log-processor
  template:
    metadata:
      labels:
        app: log-processor
    spec:
      containers:
        - name: log-processor
          image: flowlog/log-processor:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: flowlog-config
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "300m"